name = exile_alchemy
description = Alembic distillation, wiha fermentation, and basic alchemical materials for Exile.
depends = tech, liquid_store, climate, crafting, minimal, nodes_nature, ncrafting, health, exile_advanced_ceramics
supported_games = exile
author = Ozcodex

license = Unlicense
